user.name = "James McKaskill"
ui.default-command = "status"
ui.editor = "vim"
ui.diff.tool = ["difft", "--color=always", "$left", "$right"]
git.auto-local-branch = true
revsets.log = "(main..@)::"
ui.pager = "less --quit-if-one-screen --RAW-CONTROL-CHARS --chop-long-lines --no-init --mouse --use-color"
#ui.log-word-wrap = true
aliases.l = ["log", "-T", "builtin_log_oneline"]
aliases.ld = ["log", "--no-graph", "-T", "builtin_log_detailed"]
aliases.bl = ["branch", "list"]
aliases.bt = ["branch", "list", "-T", "branch_with_timestamp", "--color=always"]

[template-aliases]
'format_short_id(id)' = 'id.shortest(6)'
'format_short_signature(signature)' = 'signature.name()'
'format_timestamp(timestamp)' = 'timestamp.format("W%V-%u")'
branch_with_timestamp = '''
if(normal_target,
	separate(" ",
		self.normal_target().committer().timestamp().format("W%V-%u"),
		label("branch", self.name()),
		self.normal_target().author().name(),
	)
 ++ "\n"
)'''
